### ISSUE TITLE
Race if an event is firing before login

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#16]
```
matrix-reminder-bot    | 2020-06-10 10:00:49,919 | matrix_reminder_bot.storage [INFO] Database initialization of type 'sqlite' complete
matrix-reminder-bot    | 2020-06-10 10:00:49,920 | apscheduler.scheduler [INFO] Scheduler started
matrix-reminder-bot    | 2020-06-10 10:00:49,922 | apscheduler.scheduler [INFO] Added job "Reminder._fire" to job store "default"
matrix-reminder-bot    | 2020-06-10 10:00:49,944 | apscheduler.scheduler [INFO] Removed job ec0199a64cea425289fa2a6b1c711d5b
matrix-reminder-bot    | 2020-06-10 10:00:49,948 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: date[2020-06-10 10:00:49 UTC], next run at: 2020-06-10 10:00:49 UTC)" (scheduled at 2020-06-10 10:00:49.922145+00:00)
matrix-reminder-bot    | 2020-06-10 10:00:49,965 | apscheduler.executors.default [ERROR] Job "Reminder._fire (trigger: date[2020-06-10 10:00:49 UTC], next run at: 2020-06-10 10:00:49 UTC)" raised an exception
matrix-reminder-bot    | Traceback (most recent call last):
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 29, in run_coroutine_job
matrix-reminder-bot    |     retval = await job.func(*job.args, **job.kwargs)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/matrix_reminder_bot/reminder.py", line 116, in _fire
matrix-reminder-bot    |     await send_text_to_room(self.client, self.room_id, message, notice=False)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/matrix_reminder_bot/chat_functions.py", line 45, in send_text_to_room
matrix-reminder-bot    |     await client.room_send(
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/nio/client/base_client.py", line 103, in wrapper
matrix-reminder-bot    |     raise LocalProtocolError("Not logged in.")
matrix-reminder-bot    | nio.exceptions.LocalProtocolError: Not logged in.
matrix-reminder-bot    | 2020-06-10 10:00:50,676 | matrix_reminder_bot.main [INFO] Logged in as ....
```

**Comment by anoadragon453** [comment]
This was a repeating reminder that should've gone off while the bot was offline.

My theory is that the scheduler is told the start_time and recurring time and immediately fires it as the start time is in the past.

We need to hand it the next future start time if the original start time was in the past.

**Comment by anoadragon453** [comment]
I've prevented the bot from firing reminders until it is logged in: d8f9b7f0e45cefa73da9670b8852deff2002c45e

> If the start time was updated each time the event fires, we'd know if the bot was down while it should have fired, and able to catch up.

The bot will just fire on the next recurring timer, but it won't fire reminders it missed. This is to prevent them from building up.
