### ISSUE TITLE
Room id not found

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#19]
Edit: this is the docker image `anoa/matrix-reminder-bot               latest              d52390be2fa7        16 hours ago`.

```
matrix-reminder-bot    | 2020-06-11 13:17:12,166 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: date[2020-06-11 13:17:11 UTC], next run at: 2020-06-11 13:17:11 UTC)" (scheduled at 2020-06-11 13:17:11.432285+00:00)
matrix-reminder-bot    | 2020-06-11 13:17:12,172 | apscheduler.executors.default [ERROR] Job "Reminder._fire (trigger: date[2020-06-11 13:17:11 UTC], next run at: 2020-06-11 13:17:11 UTC)" raised an exception
matrix-reminder-bot    | Traceback (most recent call last):
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 1452, in room_send
matrix-reminder-bot    |     room = self.rooms[room_id]
matrix-reminder-bot    | KeyError: '!pmwiththebot:myserver'
matrix-reminder-bot    |
matrix-reminder-bot    | During handling of the above exception, another exception occurred:
matrix-reminder-bot    |
matrix-reminder-bot    | Traceback (most recent call last):
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 29, in run_coroutine_job
matrix-reminder-bot    |     retval = await job.func(*job.args, **job.kwargs)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/matrix_reminder_bot/reminder.py", line 116, in _fire
matrix-reminder-bot    |     await send_text_to_room(self.client, self.room_id, message, notice=False)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/matrix_reminder_bot/chat_functions.py", line 45, in send_text_to_room
matrix-reminder-bot    |     await client.room_send(
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/nio/client/async_client.py", line 1454, in room_send
matrix-reminder-bot    |     raise LocalProtocolError(
matrix-reminder-bot    | nio.exceptions.LocalProtocolError: No such room with id !pmwiththebot:myserver found.
```

**Comment by HarHarLinks** [comment]
This has been resolved by fixing an upgrade error (re-add missing cron to row that lost it).

Weird however that it threw the error at the room id instead of indicating missing cron.

**Comment by anoadragon453** [comment]
I think this may have been another instance of us attempting to send a message before the bot had finished logging in, which should've been fixed in https://github.com/anoadragon453/matrix-reminder-bot/commit/d8f9b7f0e45cefa73da9670b8852deff2002c45e.

If you experience this behaviour again, please reopen this issue.
