### ISSUE TITLE
Crash due to time zones

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#39]
```
matrix-reminder-bot    | 2020-07-23 22:47:09,078 | matrix_reminder_bot.main [INFO] Logged in as @matrix-reminder-bot:myserver.tld
matrix-reminder-bot    | 2020-07-23 22:47:09,078 | matrix_reminder_bot.main [INFO] Startup complete
matrix-reminder-bot    | 2020-07-23 22:47:09,079 | matrix_reminder_bot.main [ERROR] Unknown exception occurred:
matrix-reminder-bot    | Traceback (most recent call last):
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/matrix_reminder_bot/main.py", line 108, in main
matrix-reminder-bot    |     SCHEDULER.start()
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 162, in start
matrix-reminder-bot    |     self._real_add_job(job, jobstore_alias, replace_existing)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 859, in _real_add_job
matrix-reminder-bot    |     replacements['next_run_time'] = job.trigger.get_next_fire_time(None, now)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/apscheduler/triggers/interval.py", line 66, in get_next_fire_time
matrix-reminder-bot    |     return self.timezone.normalize(next_fire_time)
matrix-reminder-bot    |   File "/usr/local/lib/python3.8/site-packages/pytz/tzinfo.py", line 252, in normalize
matrix-reminder-bot    |     offset = dt.tzinfo._utcoffset
matrix-reminder-bot    | AttributeError: 'datetime.timezone' object has no attribute '_utcoffset'
matrix-reminder-bot    | 2020-07-23 22:47:09,081 | matrix_reminder_bot.main [WARNING] Restarting in 15s...
```

**Comment by anoadragon453** [comment]
Fixed in be281c6.
